routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes(['verify'=>true]);


Route::group(['middleware' => ['auth','verified']], function () {

    Route::get('link-tree-view',['uses'=>'LinkController@manageLink']);
    Route::post('add-link',['as'=>'add.link','uses'=>'LinkController@addLink']);

    Route::get('/links', 'LinkController@index')->name('links.index');
    Route::get('/links/tableau/{link}', [
        'as' => 'tableau',
        'uses' => 'LinkController@tableau'
    ]);
    Route::resource('links', 'LinkController');


    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('/components', function(){
        return view('components');
    })->name('components');


    Route::resource('users', 'UserController');

    Route::get('/profile/{user}', 'UserController@profile')->name('profile.edit');

    Route::post('/profile/{user}', 'UserController@profileUpdate')->name('profile.update');

    Route::resource('roles', 'RoleController')->except('show');


    Route::resource('category', 'CategoryController')->except('show');

    Route::resource('post', 'PostController');
    Route::resource('data', 'DataController');

    Route::get('/activity-log', 'SettingController@activity')->name('activity-log.index');

    Route::get('/settings', 'SettingController@index')->name('settings.index');

    Route::post('/settings', 'SettingController@update')->name('settings.update');
    Route::get('/userprofile', 'UserProfileController@index');
    Route::post('/userprofile', 'UserProfileController@update');


    Route::get('media', function (){
        return view('media.index');
    })->name('media.index');
});

resources/views/includes/header.blade.php
<nav class="navbar navbar-top navbar-expand navbar-dark">
    <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Search form -->
            <!-- <form class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
                <div class="form-group mb-0">
                    <div class="input-group input-group-alternative input-group-merge">
                        <div class="input-group-prepend">
                            <span class="input-group-text"><i class="fas fa-search"></i></span>
                        </div>
                        <input class="form-control" placeholder="Search" type="text">
                    </div>
                </div>
                <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </form> -->
            <!-- Navbar links -->
            <ul class="navbar-nav align-items-center  ml-md-auto ">
                <li class="nav-item d-xl-none">
                    <!-- Sidenav toggler -->
                    <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                        <div class="sidenav-toggler-inner">
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                            <i class="sidenav-toggler-line"></i>
                        </div>
                    </div>
                </li>
                <li class="nav-item d-sm-none">
                    <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
                        <i class="ni ni-zoom-split-in"></i>
                    </a>
                </li>
                
            </ul>
            <img src="{{asset('assets/img/logo1.png')}}" style="width:100px;heigh:100px;">
            <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
                <li class="nav-item dropdown">
                    <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <div class="media align-items-center">
                  <!-- <span class="avatar avatar-sm rounded-circle">
                    @if (Auth::user()->profile_photo)
                        <img width="45" height="45" class="img-fluid rounded-pill" src="{{ asset(Auth::user()->profile_photo) }}" alt="">
                    @else
                    <i class="far avatar avatar-sm rounded-circle fa-user"></i>

                    @endif
                  </span> -->
                            <div class="media-body  ml-2  d-none d-lg-block">
                                <span class="mb-0 text-sm  font-weight-bold">{{ Auth::user()->name }}</span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu  dropdown-menu-right ">
                        <a href="{{ route('profile.edit', auth()->user()) }}" class="dropdown-item">
                            <i class="ni ni-single-02"></i>
                            <span>My profile</span>
                        </a>
                        @can('settings.update')

                        <a href="{{ route('settings.index') }}" class="dropdown-item">
                            <i class="ni ni-settings-gear-65"></i>
                            <span>Settings</span>
                        </a>
                        @endcan
                        <!-- <a href="#!" class="dropdown-item">
                            <i class="ni ni-support-16"></i>
                            <span>Support</span>
                        </a> -->
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{{ route('logout') }}"
                           onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="ni ni-user-run"></i>
                            <span>Logout</span>
                        </a>
                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                            @csrf
                        </form>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/includes/navbar.blade.php
<?php
use App\Link;
$links = Link::where('parent_id', '=', 0)->get();
$allLinks = Link::pluck('link','id')->all();
$root = Link::where('parent_id', '=', 0)->first();

$user = \Auth::user();
?>
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs " id="sidenav-main" style="height: 100%;background-color: black;opacity: 1;">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  d-flex  align-items-center text-light" >
            <a style="color:white" class="navbar-brand  " href="{{ route('home') }}" data-toggle="tooltip" data-original-title="{{ setting('company_name') }}">
            {{ substr(setting('company_name'), 0, 22) }}
            </a>
            <div class=" ml-auto ">
                <!-- Sidenav toggler -->
                <div class="sidenav-toggler d-none d-xl-block" data-action="sidenav-unpin" data-target="#sidenav-main">
                    <div class="sidenav-toggler-inner">
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                        <i class="sidenav-toggler-line"></i>
                    </div>
                </div>
            </div>
        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <!-- Nav items -->
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link {{ (request()->is('home*')) ? 'active' : '' }}" href="{{route('home')}}">
                            <i class="ni ni-shop text-primary"></i>
                            <span class="nav-link-text" >Dashboard</span>
                        </a>
                    </li>
                    @can('update-settings')
                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('settings*')) ? 'active' : '' }}" href="{{route('settings.index')}}">
                                <i class="ni ni-settings-gear-65 text-primary"></i>
                                <span class="nav-link-text">Manage Settings</span>
                            </a>
                        </li>
                    @endcan
                    @canany(['view-link', 'create-link'])
                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('links*')) ? 'active' : '' }}" href="{{route('links.index')}}">
                                <i class="ni ni-settings-gear-65 text-primary"></i>
                                <span class="nav-link-text">Manage Links</span>
                            </a>
                        </li>
                    @endcan

                  
                    @canany(['view-user', 'create-user'])
                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('users*')) ? 'active' : '' }}" href="#navbar-users"  data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-users">
                                <i class="fas text-primary fa-tasks"></i>
                                <span class="nav-link-text">Manage Users</span>
                            </a>
                            <div class="collapse" id="navbar-users">
                                <ul class="nav nav-sm flex-column">
                                 @can('view-user')
                                    <li class="nav-item">
                                        <a href="{{route('users.index')}}" class="nav-link"><span class="sidenav-mini-icon"></span><span class="sidenav-normal">All Users</span></a>
                                    </li>
                                    @endcan
                                    <li class="nav-item">
                                        <a href="{{route('users.create')}}" class="nav-link"><span class="sidenav-mini-icon"></span><span class="sidenav-normal">Add New User</span></a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                    @endcan

                    @canany(['view-data', 'create-data'])

                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('data*')) ? 'active' : '' }}" href="#navbar-data"  data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-data">
                                <i class="fas text-primary fa-tasks"></i>
                                <span class="nav-link-text">Manage Data</span>
                            </a>
                            <div class="collapse" id="navbar-data">
                                <ul class="nav nav-sm flex-column">
                                 @can('view-data')
                                    <li class="nav-item">
                                        <a href="{{route('data.index')}}" class="nav-link"><span class="sidenav-mini-icon">D </span><span class="sidenav-normal">All Data</span></a>
                                    </li>
                                    @endcan
                                </ul>
                            </div>
                        </li>
                    @endcan

                    
                    @canany(['view-role', 'create-role'])
                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('roles*')) ? 'active' : '' }}" href="{{route('roles.index')}}">
                                <i class="fas fa-lock text-primary"></i>
                                <span class="nav-link-text">Manage Roles</span>
                            </a>
                        </li>
                    @endcan

             
                    @canany(['view-activity-log'])
                        <li class="nav-item">
                            <a class="nav-link {{ (request()->is('activity-log*')) ? 'active' : '' }}" href="{{route('activity-log.index')}}">
                                <i class="fas fa-history text-primary"></i>
                                <span class="nav-link-text">Activity Log</span>
                            </a>
                        </li>
                    @endcan

                    @if(!is_null($root))
                    <?php $counter = 0; ?>
                    @foreach($links as $link)
                    @canany([$link->link])
                        @if(count($link->childs))
                        <li class="nav-item">
                            <a class="nav-link" href="#navbar-link-parent{{ $link->link }}"  data-toggle="collapse" role="button" aria-expanded="true" aria-controls="navbar-link-parent{{ $link->link }}">
                                <i class="fas text-primary fa-book"></i>
                                <span class="nav-link-text">{{ $link->link }}</span>
                            </a>
                            <div class="collapse" id="navbar-link-parent{{ $link->link }}">
                                <ul class="nav nav-sm flex-column" >
                                    @include('manageChildNavBar',['childs' => $link->childs, 'level' => $counter])
                                </ul>
                            </div>
                        </li>
                        @else
                            <li class="nav-item">
                                <a href="{{route('links.show', $link)}}" class="nav-link">
                                    <i class="fas text-primary fa-link"></i>
                                    <span class="sidenav-mini-icon"></span>
                                    <span class="sidenav-normal">{{ $link->link }}</span>
                                </a>
                            </li>
                        @endif
                        <?php $counter = $counter + 1; ?>
                        @endcan
                    @endforeach
                    @endif
                 
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/includes/page-header.blade.php
<div class="header pb-6">
    <div class="container-fluid">
        <div class="header-body">
            <div class="row align-items-center pb-4">
                <div class="col-lg-6 col-7">
                    <h1 class="text-white d-inline-block mb-0">{{ ($title ?? '') }}</h1>
                </div>
                <div class="col-lg-6 col-5 text-right">
                    @stack('pg_btn')
                </div>
                <div class="col-lg-12 col-12">
                    @include('flash::message')
                    @if ($errors->any())
                    @foreach ($errors->all() as $error)
                        <div class="alert alert-danger mt-4">{{$error}}</div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>